### ISSUE TITLE
Incorrect AB rotation

### ISSUE THREAD

**Issue by ExInferi** [Starur/Alt1TravellingMerchant#2]
Today, it displays small and medium menaphite gift offerings in A/B, while it should display damage enhancer and horn of honour

**Comment by Starur** [comment]
@ExInferi 
Thanks for reaching out. This should be fixed now with this PR: /pull/1
If you still have some errors the cache needs to be cleared.

**Comment by ExInferi** [comment]
Fixed, thanks!

**Comment by ExInferi** [comment]
Showing wrong stock again today, heard this was an issue with merchant bot as well. Showing 2x Gift and Trisk key, but actual stock is 2x Fishbowl and DTD. Noticed wiki now states there's an algorithm issue:
https://runescape.wiki/w/Travelling_Merchant%27s_Shop/Future
